[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "python -m nltk.downloader vader_lexicon punkt stopwords"
]

[start]
cmd = "cd backend && python app.py"